language: cpp

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update

install:
   - sudo apt-get install --force-yes premake4
   - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
   - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

compiler:
  - gcc
before_script:
   - premake4 gmake
script:
   - make && ./Test