language: cpp
compiler:
  - gcc
before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update

install:
   - sudo apt-get install --force-yes premake4
   - sudo apt-get install -qq gcc-4.8
   - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 100
   - sudo update-alternatives --config gcc
before_script:
   - gcc -v
   - premake4 gmake
script:
   - make verbose=true
   - ./Test