language: cpp

before_install:
  - sudo add-apt-repository -y ppa:codegear/release
  - sudo apt-get update

install:
   - sudo apt-get install --force-yes premake4

compiler:
  - gcc
before_script:
   - premake4 gmake
script:
   - make